In [1]:
import requests
import json
import pandas as pd
CC = 252321
R = 842
url='https://comtrade.un.org/api/get?r='+str(R)+'&px=HS&ps=2020%2C2019%2C2018%2C2017%2C2016&rg=1&p=0&cc='+str(CC)+'&type=c&freq=a'
res = requests.get(url).json()

In [2]:
res

{'validation': {'status': {'name': 'Ok',
   'value': 0,
   'category': 0,
   'description': '',
   'helpUrl': 'For more reference visit http://comtrade.un.org/data/dev/portal/'},
  'message': None,
  'count': {'value': 5,
   'started': '2022-04-02T13:14:36.7368202+02:00',
   'finished': '2022-04-02T13:14:37.2224005+02:00',
   'durationSeconds': 0.48558029999999996},
  'datasetTimer': {'started': '2022-04-02T13:14:36.7368202+02:00',
   'finished': '2022-04-02T13:14:38.2862747+02:00',
   'durationSeconds': 1.5494545}},
 'dataset': [{'pfCode': 'H5',
   'yr': 2017,
   'period': 2017,
   'periodDesc': '2017',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1277982000,
   'AltQuantity': None,
   'NetWeight': 1277982000,
   'GrossWeight': None,
   'TradeValue': 174024325,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H5',
   'yr': 2018,
   'period': 2018,
   'periodDesc': '2018',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1410560000,
   'AltQuantity': None,
   'NetWeight': 1410560000,
   'GrossWeight': None,
   'TradeValue': 190127416,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H5',
   'yr': 2019,
   'period': 2019,
   'periodDesc': '2019',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1411709000,
   'AltQuantity': None,
   'NetWeight': 1411709000,
   'GrossWeight': None,
   'TradeValue': 190798454,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H5',
   'yr': 2020,
   'period': 2020,
   'periodDesc': '2020',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1146336000,
   'AltQuantity': None,
   'NetWeight': 1146336000,
   'GrossWeight': None,
   'TradeValue': 171212775,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H4',
   'yr': 2016,
   'period': 2016,
   'periodDesc': '2016',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1274782000,
   'AltQuantity': None,
   'NetWeight': 1274782000,
   'GrossWeight': None,
   'TradeValue': 166960521,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0}]}

In [3]:
json_object = json.dumps(res['dataset'], indent = 4)
  
# Writing to sample.json
with open("sample.json", "w") as outfile:
    outfile.write(json_object)

In [4]:
df_json = pd.read_json('sample.json')
df_json.to_excel('DATAFILE.xlsx')

In [5]:
praveen=pd.read_excel('DATAFILE.xlsx', index_col=0)

In [6]:
praveen

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,...,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H5,2017,2017,2017,6,1,1,Import,842,USA,...,NaN,NaN,1277982000,NaN,1277982000,NaN,174024325,NaN,NaN,0
1,H5,2018,2018,2018,6,1,1,Import,842,USA,...,NaN,NaN,1410560000,NaN,1410560000,NaN,190127416,NaN,NaN,0
2,H5,2019,2019,2019,6,1,1,Import,842,USA,...,NaN,NaN,1411709000,NaN,1411709000,NaN,190798454,NaN,NaN,0
3,H5,2020,2020,2020,6,1,1,Import,842,USA,...,NaN,NaN,1146336000,NaN,1146336000,NaN,171212775,NaN,NaN,0
4,H4,2016,2016,2016,6,1,1,Import,842,USA,...,NaN,NaN,1274782000,NaN,1274782000,NaN,166960521,NaN,NaN,0

In [7]:
praveen.columns

Index(['pfCode', 'yr', 'period', 'periodDesc', 'aggrLevel', 'IsLeaf', 'rgCode',
       'rgDesc', 'rtCode', 'rtTitle', 'rt3ISO', 'ptCode', 'ptTitle', 'pt3ISO',
       'ptCode2', 'ptTitle2', 'pt3ISO2', 'cstCode', 'cstDesc', 'motCode',
       'motDesc', 'cmdCode', 'cmdDescE', 'qtCode', 'qtDesc', 'qtAltCode',
       'qtAltDesc', 'TradeQuantity', 'AltQuantity', 'NetWeight', 'GrossWeight',
       'TradeValue', 'CIFValue', 'FOBValue', 'estCode'],
      dtype='object')

In [8]:
Tradequan=praveen[['yr','rgDesc','ptTitle','NetWeight','cmdCode','qtDesc']]

In [9]:
Tradequan

     yr  rgDesc ptTitle   NetWeight  cmdCode               qtDesc
0  2017  Import   World  1277982000   252321  Weight in kilograms
1  2018  Import   World  1410560000   252321  Weight in kilograms
2  2019  Import   World  1411709000   252321  Weight in kilograms
3  2020  Import   World  1146336000   252321  Weight in kilograms
4  2016  Import   World  1274782000   252321  Weight in kilograms

In [10]:
value=praveen[['yr','rgDesc','TradeValue','ptTitle','cmdCode']]

In [11]:
value

     yr  rgDesc  TradeValue ptTitle  cmdCode
0  2017  Import   174024325   World   252321
1  2018  Import   190127416   World   252321
2  2019  Import   190798454   World   252321
3  2020  Import   171212775   World   252321
4  2016  Import   166960521   World   252321

In [12]:
url1='https://comtrade.un.org/api/get?r='+str(R)+'&px=HS&ps=2020%2C2019%2C2018%2C2017%2C2016&rg=2&p=0&cc='+str(CC)+'&type=c&freq=a'
res1 = requests.get(url).json()

In [13]:
res1

{'validation': {'status': {'name': 'Ok',
   'value': 0,
   'category': 0,
   'description': '',
   'helpUrl': 'For more reference visit http://comtrade.un.org/data/dev/portal/'},
  'message': None,
  'count': {'value': 5,
   'started': '2022-04-02T13:14:36.7368202+02:00',
   'finished': '2022-04-02T13:14:37.2224005+02:00',
   'durationSeconds': 0.48558029999999996},
  'datasetTimer': {'started': '2022-04-02T13:14:36.7368202+02:00',
   'finished': '2022-04-02T13:14:38.2862747+02:00',
   'durationSeconds': 1.5494545}},
 'dataset': [{'pfCode': 'H5',
   'yr': 2017,
   'period': 2017,
   'periodDesc': '2017',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1277982000,
   'AltQuantity': None,
   'NetWeight': 1277982000,
   'GrossWeight': None,
   'TradeValue': 174024325,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H5',
   'yr': 2018,
   'period': 2018,
   'periodDesc': '2018',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1410560000,
   'AltQuantity': None,
   'NetWeight': 1410560000,
   'GrossWeight': None,
   'TradeValue': 190127416,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H5',
   'yr': 2019,
   'period': 2019,
   'periodDesc': '2019',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1411709000,
   'AltQuantity': None,
   'NetWeight': 1411709000,
   'GrossWeight': None,
   'TradeValue': 190798454,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H5',
   'yr': 2020,
   'period': 2020,
   'periodDesc': '2020',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1146336000,
   'AltQuantity': None,
   'NetWeight': 1146336000,
   'GrossWeight': None,
   'TradeValue': 171212775,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0},
  {'pfCode': 'H4',
   'yr': 2016,
   'period': 2016,
   'periodDesc': '2016',
   'aggrLevel': 6,
   'IsLeaf': 1,
   'rgCode': 1,
   'rgDesc': 'Import',
   'rtCode': 842,
   'rtTitle': 'USA',
   'rt3ISO': 'USA',
   'ptCode': 0,
   'ptTitle': 'World',
   'pt3ISO': 'WLD',
   'ptCode2': None,
   'ptTitle2': '',
   'pt3ISO2': '',
   'cstCode': '',
   'cstDesc': '',
   'motCode': '',
   'motDesc': '',
   'cmdCode': '252321',
   'cmdDescE': 'Cement; portland, white, whether or not artificially coloured',
   'qtCode': 8,
   'qtDesc': 'Weight in kilograms',
   'qtAltCode': None,
   'qtAltDesc': '',
   'TradeQuantity': 1274782000,
   'AltQuantity': None,
   'NetWeight': 1274782000,
   'GrossWeight': None,
   'TradeValue': 166960521,
   'CIFValue': None,
   'FOBValue': None,
   'estCode': 0}]}

In [14]:
json_object1 = json.dumps(res1['dataset'], indent = 4)
  
# Writing to sample.json
with open("sample1.json", "w") as outfile:
    outfile.write(json_object1)

In [15]:
df_json1 = pd.read_json('sample1.json')
df_json1.to_excel('DATAFILE1.xlsx')

In [16]:
praveen1=pd.read_excel('DATAFILE1.xlsx', index_col=0)

In [17]:
Tradequan1=praveen1[['yr','rgDesc','ptTitle','NetWeight','cmdCode','qtDesc']]

In [18]:
value1=praveen1[['yr','rgDesc','TradeValue','ptTitle','cmdCode']]

In [19]:
import requests
import json
import pandas as pd
CC = 252321
R = 842
url2='https://comtrade.un.org/api/get?r='+str(R)+'&px=HS&ps=2015%2C2021&rg=1&p=0&cc='+str(CC)+'&type=c&freq=a'
res2 = requests.get(url2).json()
json_object2 = json.dumps(res2['dataset'], indent = 4)
  
# Writing to sample.json
with open("sample2.json", "w") as outfile:
    outfile.write(json_object2)

In [20]:
df_json2 = pd.read_json('sample2.json')
df_json2.to_excel('DATAFILE2.xlsx')
praveen2=pd.read_excel('DATAFILE2.xlsx', index_col=0)

In [21]:
praveen2

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,...,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H5,2021,2021,2021,6,1,1,Import,842,USA,...,NaN,NaN,1805909000,NaN,1805909000,NaN,194474719,NaN,NaN,0
1,H4,2015,2015,2015,6,1,1,Import,842,USA,...,NaN,NaN,1135679992,NaN,1135679992,NaN,152828683,NaN,NaN,0

In [22]:
Tradequan2=praveen2[['yr','rgDesc','ptTitle','NetWeight','cmdCode','qtDesc']]

In [23]:
value2=praveen2[['yr','rgDesc','TradeValue','ptTitle','cmdCode']]

In [24]:
import requests
import json
import pandas as pd
CC = 252321
R = 842
url3='https://comtrade.un.org/api/get?r='+str(R)+'&px=HS&ps=2015%2C2021&rg=2&p=0&cc='+str(CC)+'&type=c&freq=a'
res3 = requests.get(url3).json()
json_object3 = json.dumps(res3['dataset'], indent = 4)
  
# Writing to sample.json
with open("sample3.json", "w") as outfile:
    outfile.write(json_object3)

In [25]:
df_json3 = pd.read_json('sample3.json')
df_json3.to_excel('DATAFILE3.xlsx')
praveen3=pd.read_excel('DATAFILE3.xlsx', index_col=0)

In [26]:
praveen3

,pfCode,yr,period,periodDesc,aggrLevel,IsLeaf,rgCode,rgDesc,rtCode,rtTitle,...,qtAltCode,qtAltDesc,TradeQuantity,AltQuantity,NetWeight,GrossWeight,TradeValue,CIFValue,FOBValue,estCode
0,H5,2021,2021,2021,6,1,2,Export,842,USA,...,NaN,NaN,56897000,NaN,56897000,NaN,12264462,NaN,NaN,0
1,H4,2015,2015,2015,6,1,2,Export,842,USA,...,NaN,NaN,194777000,NaN,194777000,NaN,39956893,NaN,NaN,0

In [27]:
Tradequan3=praveen3[['yr','rgDesc','ptTitle','NetWeight','cmdCode','qtDesc']]

In [28]:
value3=praveen3[['yr','rgDesc','TradeValue','ptTitle','cmdCode']]

In [29]:
writer = pd.ExcelWriter('Ugadi.xlsx', engine='xlsxwriter')

In [30]:
Tradequan.to_excel(writer, sheet_name='Totalimpquan')
value.to_excel(writer, sheet_name='Totalimpval')
Tradequan1.to_excel(writer, sheet_name='Totalexpquan')
value1.to_excel(writer, sheet_name='Totalexpval')
Tradequan3.to_excel(writer, sheet_name='Imp20152021')
value3.to_excel(writer, sheet_name='Exp20152021')

In [31]:
writer.save()